services:
  - type: web
    name: findmycamp
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: findmycamp-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    plan: free

databases:
  - name: findmycamp-db
    databaseName: findmycamp
    user: findmycamp_user
    plan: free
    ipAllowList:
      - 0.0.0.0/0
