services:
  - type: web
    name: findmycamp
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
databases:
  - name: findmycamp-db
    databaseName: findmycamp
    user: findmycamp_user
    plan: free
