services:
  - type: web
    name: findmycamp
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
    region: oregon
    plan: free
databases:
  - name: findmycamp-db
    databaseName: findmycamp
    user: findmycamp_user
    plan: free
